### ISSUE TITLE
Adding a Contributors Guideline

### ISSUE THREAD

**Issue by aakankshabhende** [japneetbhatia/White-Board#1]

**Comment by shindesuyog** [comment]
i will like to add Contributors Guideline in Readme file. please assign this to me

**Comment by japneetkaurbhatia** [comment]
@aakankshabhende @shindesuyog join slack channel first

**Comment by aakankshabhende** [comment]
I joined the channel the channel @japneetbhatia mam.
Now please assign this issue to me

**Comment by swathi-469** [comment]
I would like to work on this issue ..  please assign me I am beginner in open source  I am  ready with readme file .... So If assigned I would immediately work on it

**Comment by swathi-469** [comment]
Shall I work on this issue please assign this to me

**Comment by lipiseth** [comment]
I would like to work on this issue please assign and guide me , if I get this assigned by you , this would be the  first step to my open source journey.
