### ISSUE TITLE
Adding a colour 

### ISSUE THREAD

**Issue by devesh-2002** [japneetbhatia/White-Board#12]
I am a contributor from devincept and this is my first issue. I would like to add a 'grey' color among the other colours. Can you please assign this issue to me?

**Comment by sravanyabendi** [comment]
Can you please assign me to this issue?

**Comment by japneetkaurbhatia** [comment]
There is already a color-picker

**Comment by devesh-2002** [comment]
But there isn't a grey colour, if I am not wrong.
