### ISSUE TITLE
Add notes feature

### ISSUE THREAD

**Issue by japneetkaurbhatia** [japneetbhatia/White-Board#19]

**Comment by payaldutta** [comment]
@japneetbhatia Can you please describe this issue?

**Comment by japneetkaurbhatia** [comment]
whenever a notes icon is clicked a modal get open where you can write text

Similar to text box

**Comment by vanishasamriddhi** [comment]
I can create a page using JavaScript where one can write notes and the notes would get saved to there local server.
If it's okay then, I can do this but I need time (3-4 days)

**Comment by Naman-mahi** [comment]
Sir please can you assign to me this one..
