### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by japneetkaurbhatia** [japneetbhatia/White-Board#30]

**Comment by Naman-mahi** [comment]
Can you tell me what to update in readme file?

**Comment by Naman-mahi** [comment]
And sir kya can assign to me

**Comment by Naman-mahi** [comment]
And sir can you please assign to me

**Comment by aniket-2001** [comment]
I want to contribute to the readme file can you please assign me this task

**Comment by japneetkaurbhatia** [comment]
Just change the image and add features if missing
