### ISSUE TITLE
Create CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by payaldutta** [japneetbhatia/White-Board#4]
I want to create a code of conduct file for those who are new to open source. @japneetbhatia  Can I work on this?

**Comment by japneetkaurbhatia** [comment]
join slack channel #white-board first

**Comment by swathi-469** [comment]
I would like to work on this issue , I joined slack also please assign me

**Comment by payaldutta** [comment]
Do assign me this issue so that I can start working on it. @japneetbhatia

**Comment by japneetkaurbhatia** [comment]
@payaldutta  you haven't joined slack channel

**Comment by swathi-469** [comment]
ok sir I will work on the issue

**Comment by swathi-469** [comment]
I have made my pull request can you check it

**Comment by payaldutta** [comment]
@swathi-469 Hey dear if someone has created an issue it's obvious that they are going to resolve it. So, please search for issues that already exist or make your own issue if needed. **Don't grab others!**
Good Luck!

**Comment by payaldutta** [comment]
@japneetbhatia I have joined slack and I wasn't able to respond yesterday due to some technical problem.
And as you had assigned this issue to someone else, please mention some beginner-friendly issues for me to work on.
It will be very kind of you.
Thank you.

**Comment by japneetkaurbhatia** [comment]
@payaldutta I open some new issue you can check those
