### ISSUE TITLE
Creating pdf of canvas

### ISSUE THREAD

**Issue by Sshashank0743** [japneetbhatia/White-Board#5]
I want to add one picture where we will show how the board will look after drawing and two more features for this **whiteboard**.

**Comment by 123mansha** [comment]
@Sshashank0743 Please be more specific and if possible add photos in the comment section to describe the feature more accurately.

**Comment by Sshashank0743** [comment]
I don't know whether it will be beneficial or not but Currently, I am looking to add these two features to the whiteboard. Like if any instructor or teacher uses this whiteboard then he can also share some important notes by PDF sharing.

Featues:
* Canvas
* PDF sharing

**Comment by japneetkaurbhatia** [comment]
downloading a pdf of a canvas ? right ?

**Comment by Sshashank0743** [comment]
Yes

**Comment by Jayshree-2111** [comment]
I can save in pdf format and print the content of White-Board. Can you assign it to me?

**Comment by 123mansha** [comment]
@Sshashank0743 is the task done?
It's already been 8 days.
Please give updates about the progress.

**Comment by Sshashank0743** [comment]
Can you assign someone else? Sorry for the late response.

**Comment by 123mansha** [comment]
@Jayshree-2111 u can take up the issue.
