### ISSUE TITLE
Adding Header At Top 

### ISSUE THREAD

**Issue by japneetkaurbhatia** [japneetbhatia/White-Board#8]
Head Bar contains Heading "White-Board"

**Comment by harshita9621** [comment]
Can I work on this issue

**Comment by sravanyabendi** [comment]
Can you please assign me to this issue?

**Comment by harshita9621** [comment]
@japneetbhatia Can you please explain in header what I have to add.

**Comment by japneetkaurbhatia** [comment]
make header and add heading on top "White-board"

**Comment by japneetkaurbhatia** [comment]
@harshita9621 still have any issue than you can message me on slack

**Comment by japneetkaurbhatia** [comment]
@harshita9621 Are you working on this ?

**Comment by harshita9621** [comment]
@japneetbhatia Tomorrow I make the PR.

**Comment by harshita9621** [comment]
![Screenshot (262)](https://user-images.githubusercontent.com/57454733/126029182-416e011c-7513-48d2-8fd6-5b079e3cc2d2.png)

@japneetbhatia Please have a look on header it's okk our I have to make the changes on it.

**Comment by japneetkaurbhatia** [comment]
its fine

**Comment by harshita9621** [comment]
@japneetbhatia Can I make the PR.

**Comment by Jayshree-2111** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by japneetkaurbhatia** [comment]
Yes @harshita9621

**Comment by japneetkaurbhatia** [comment]
@Jayshree-2111 already resolved
